---
project: deblur_gan
experiment_desc: exp_berlin_data_june21
continue_train: false
continue_epoch: 0

train:
  files_a: /home/shong/Berlin_data/train/images/*.png
  files_b: /home/shong/Berlin_data/train/labels/*.png
  size: &SIZE 256
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, .9]
  scope: geometric #ORG geometric
  corrupt: &CORRUPT
    - name: cutout
      prob: 0.5 #ORG 0.5
      num_holes: 0
      max_h_size: 25
      max_w_size: 25
    - name: jpeg
      quality_lower: 70 #ORG 70
      quality_upper: 90 #ORG 90
    - name: motion_blur
    - name: median_blur
    - name: gamma
    - name: rgb_shift
    - name: hsv_shift
    - name: sharpen

val:
  files_a: /home/shong/Berlin_data/test/images/*.png
  files_b: /home/shong/Berlin_data/test/labels/*.png
  size: *SIZE
  scope: geometric #ORG geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [.9, 1]
  corrupt: *CORRUPT

phase: train
warmup_num: 3 #ORG 3
model:
  g_name: fpn_inception
  blocks: 9
  d_name: double_gan #ORG double_gan # may be no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.001
  disc_loss: ragan-ls #wgan-gp #ragan-ls #wgan-gp
  learn_residual: True
  norm_layer: instance
  dropout: True

num_epochs: 300
train_batches_per_epoch: 2941
val_batches_per_epoch: 1016
batch_size: 1
image_size: [256, 256]

optimizer:
  name: adam
  lr: 0.0001 #ORG 0.0001
scheduler:
  name: linear
  start_epoch: 50
  min_lr: 0.0000001 #ORG 0.0000001


#SJ_TEST
#test_dir:  /home/shong/SFO_l26_test/

